version: "2"
services:
  sample_db-postgresql:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=game
    volumes:
      - sample_db:/var/lib/postgresql/data

volumes:
  sample_db:
